'use strict';
const OWNER='het7tejani', REPO='etsy-ledger-data', PATH='ledger.json';
const INITIAL_SHOPS=['Psychic Era','Psychic Sutra','Daisy Medium Studio','Rosy Medium Studio','LadyGeorgia'];
const enc=new TextEncoder(), dec=new TextDecoder();
const $=id=>document.getElementById(id);
let token='', key=null, salt=null, sha=null, entries=[], activeShop='', editing=null, busy=false;
const api=`https://api.github.com/repos/${OWNER}/${REPO}/contents/${PATH}`;
const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(n/100);
const bytesToBase64=bytes=>{let str='';for(let i=0;i<bytes.length;i+=8192)str+=String.fromCharCode(...bytes.slice(i,i+8192));return btoa(str)};
const base64ToBytes=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
const err=e=>{$('status').textContent=e.message||String(e);console.error(e)};
const status=s=>{$('status').textContent=s};
const setBusy=b=>{busy=b; for(const id of ['connectBtn','unlockBtn','saveBtn','deleteBtn'])$(id).disabled=b};
const auth=()=>({Authorization:`Bearer ${token}`,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'});
async function getRemote(){const r=await fetch(api,{headers:auth(),cache:'no-store'});if(r.status===404)return null;if(!r.ok)throw Error(r.status===401||r.status===403?'Token cannot read the private ledger repository. Check its access and permissions.':`GitHub read failed (${r.status}).`);const v=await r.json();if(typeof v.content!=='string'||!v.sha)throw Error('Unexpected GitHub response.');return {body:JSON.parse(dec.decode(base64ToBytes(v.content.replace(/\s/g,'')))),sha:v.sha}}
async function putRemote(body,oldSha,message){const r=await fetch(api,{method:'PUT',headers:{...auth(),'Content-Type':'application/json'},body:JSON.stringify({message,content:bytesToBase64(enc.encode(JSON.stringify(body))),...(oldSha?{sha:oldSha}:{})})});if(!r.ok){if(r.status===409||r.status===422)throw Error('This ledger changed on another device. Reload before saving; nothing was overwritten.');throw Error(`GitHub save failed (${r.status}). Check token Contents read/write permission.`)}const j=await r.json();return j.content.sha}
async function derive(pass,s){const material=await crypto.subtle.importKey('raw',enc.encode(pass),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt:s,iterations:310000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function encryptData(items){const iv=crypto.getRandomValues(new Uint8Array(12));const ciphertext=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,enc.encode(JSON.stringify({version:1,entries:items})));return {version:1,kdf:'PBKDF2-SHA256-310000',cipher:'AES-256-GCM',salt:bytesToBase64(salt),iv:bytesToBase64(iv),data:bytesToBase64(new Uint8Array(ciphertext))}}
async function decryptData(body){if(body.version!==1||body.kdf!=='PBKDF2-SHA256-310000'||body.cipher!=='AES-256-GCM')throw Error('Unknown ledger format.');const result=await crypto.subtle.decrypt({name:'AES-GCM',iv:base64ToBytes(body.iv)},key,base64ToBytes(body.data));const parsed=JSON.parse(dec.decode(result));if(parsed.version!==1||!Array.isArray(parsed.entries))throw Error('Invalid ledger data.');return parsed.entries}
function stage(name){$('setup').hidden=name!=='setup';$('unlock').hidden=name!=='unlock';$('dashboard').hidden=name!=='dashboard';$('addBtn').hidden=name!=='dashboard';$('lockBtn').hidden=name!=='dashboard';$('disconnectBtn').hidden=name==='setup';$('passInput').value='';status('')}
async function start(){token=localStorage.getItem('etsy-ledger-token')||'';stage(token?'unlock':'setup');if(token){try{const remote=await getRemote();$('unlockTitle').textContent=remote?'Unlock ledger':'Create your master passphrase';$('createHint').hidden=!!remote;$('unlockHelp').textContent=remote?'Enter the passphrase used to encrypt this ledger. It is not stored.':'Your private ledger is empty. Choose a new passphrase to encrypt it.'}catch(e){err(e)}}}
$('connectBtn').onclick=async()=>{if(busy)return;const candidate=$('tokenInput').value.trim();if(!candidate){status('Enter a GitHub token.');return}token=candidate;setBusy(true);try{await getRemote();localStorage.setItem('etsy-ledger-token',token);$('tokenInput').value='';await start()}catch(e){token='';err(e)}finally{setBusy(false)}};
$('unlockBtn').onclick=async()=>{if(busy)return;const pass=$('passInput').value;if(!pass){status('Enter your passphrase.');return}setBusy(true);try{const remote=await getRemote();if(!remote&&pass.length<12)throw Error('Use at least 12 characters for a new passphrase.');salt=remote?base64ToBytes(remote.body.salt):crypto.getRandomValues(new Uint8Array(16));key=await derive(pass,salt);entries=remote?await decryptData(remote.body):[];sha=remote?.sha||null;if(!remote){const data=await encryptData([]);sha=await putRemote(data,null,'Initialize encrypted Etsy ledger')}stage('dashboard');render()}catch(e){key=null;entries=[];err(e.message?.includes('decrypt')?Error('Wrong passphrase or corrupted ledger.'):e)}finally{setBusy(false)}};
$('lockBtn').onclick=()=>{key=null;entries=[];sha=null;stage('unlock')};
$('disconnectBtn').onclick=()=>{key=null;entries=[];sha=null;token='';localStorage.removeItem('etsy-ledger-token');stage('setup')};
function shops(){return [...new Set([...INITIAL_SHOPS,...entries.map(e=>e.shop)])]}
function button(label,cls,handler){const el=document.createElement('button');el.type='button';el.className=cls;el.textContent=label;el.onclick=handler;return el}
function render(){const nav=$('shopNav');nav.replaceChildren();$('allNav').classList.toggle('active',!activeShop);for(const name of shops())nav.append(button(name,'nav'+(activeShop===name?' active':''),()=>{activeShop=name;render()}));$('viewTitle').textContent=activeShop||'Overview';$('subtitle').textContent=activeShop?'Payments and expenses for this shop.':'Etsy payouts and shop expenses, in one place.';const items=entries.filter(e=>!activeShop||e.shop===activeShop);const received=items.filter(e=>e.kind==='payment').reduce((s,e)=>s+e.cents,0);const expenses=items.filter(e=>e.kind==='expense').reduce((s,e)=>s+e.cents,0);$('received').textContent=money(received);$('expenses').textContent=money(expenses);$('balance').textContent=money(received-expenses);$('entryCount').textContent=`${items.length} ${items.length===1?'entry':'entries'}`;const list=$('entryList');list.replaceChildren();const sorted=[...items].sort((a,b)=>b.date.localeCompare(a.date)||b.created.localeCompare(a.created));if(!sorted.length){const blank=document.createElement('div');blank.className='empty';blank.textContent='No entries yet. Add a payment or expense to begin.';list.append(blank)}for(const item of sorted){const row=button('', 'entry',()=>openDialog(item));const left=document.createElement('span');left.className='entry-main';const title=document.createElement('span');title.className='entry-title';title.textContent=item.note|| (item.kind==='payment'?'Payment received':'Expense');const meta=document.createElement('div');meta.className='entry-meta';meta.textContent=`${item.shop}  ·  ${item.date}  ·  ${item.kind==='payment'?'Payment received':'Expense'}`;left.append(title,meta);const amount=document.createElement('span');amount.className='entry-amount '+item.kind;amount.textContent=(item.kind==='payment'?'+':'−')+money(item.cents);row.append(left,amount);list.append(row)}const opts=$('shopChoices');opts.replaceChildren();for(const name of shops()){const opt=document.createElement('option');opt.value=name;opts.append(opt)}}
$('allNav').onclick=()=>{activeShop='';render()};
function openDialog(item=null){editing=item?.id||null;$('dialogTitle').textContent=item?'Edit entry':'Add entry';$('shop').value=item?.shop||activeShop||'';$('kind').value=item?.kind||'payment';$('amount').value=item?(item.cents/100).toFixed(2):'';$('entryDate').value=item?.date||new Date().toLocaleDateString('en-CA');$('note').value=item?.note||'';$('deleteBtn').hidden=!item;$('entryDialog').showModal()}
$('addBtn').onclick=()=>openDialog();$('closeDialog').onclick=()=>$('entryDialog').close();
async function saveItems(next,message){setBusy(true);try{const data=await encryptData(next);const newSha=await putRemote(data,sha,message);sha=newSha;entries=next;$('entryDialog').close();render();status('Saved securely.')}catch(e){err(e)}finally{setBusy(false)}}
$('entryForm').onsubmit=async event=>{event.preventDefault();if(busy)return;const shop=$('shop').value.trim().replace(/\s+/g,' '), kind=$('kind').value, date=$('entryDate').value, note=$('note').value.trim(), cents=Math.round(Number($('amount').value)*100);if(!shop||!['payment','expense'].includes(kind)||!/^\d{4}-\d{2}-\d{2}$/.test(date)||!Number.isSafeInteger(cents)||cents<=0){status('Check shop, date and amount.');return}const old=entries.find(e=>e.id===editing);const entry={id:editing||crypto.randomUUID(),shop,kind,date,note,cents,created:old?.created||new Date().toISOString()};const next=editing?entries.map(e=>e.id===editing?entry:e):[...entries,entry];await saveItems(next,editing?'Edit ledger entry':'Add ledger entry')};
$('deleteBtn').onclick=async()=>{if(!editing||busy)return;if(!window.confirm('Delete this entry? Earlier encrypted versions may remain in GitHub commit history.'))return;await saveItems(entries.filter(e=>e.id!==editing),'Delete ledger entry')};
start();
